name: SpaceMouse3Dconnexion
description: The SpaceMouse3Dconnexion QGIS Plugin enables professional-grade 3D navigation in QGIS using 3DConnexion SpaceMouse devices
topics:
  - qgis
  - spacemouse
  - 3dconnexion
  - 3d-navigation
  - qgis-plugin
  - 3d-mouse
  - python
